CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(256),
    password VARCHAR(100),
    nickname VARCHAR(10) NOT NULL,
    profile_image VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    password_updated_at TIMESTAMP(6),
    nickname_updated_at TIMESTAMP(6),
    profile_updated_at TIMESTAMP(6),
    user_deleted BOOLEAN NOT NULL,
    deleted_at TIMESTAMP(6)
);

CREATE TABLE posts (
    post_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    like_count INTEGER NOT NULL,
    view_count INTEGER NOT NULL,
    comment_count INTEGER NOT NULL,
    commentable BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    post_deleted BOOLEAN NOT NULL,
    deleted_at TIMESTAMP(6),
    CONSTRAINT fk_posts_user
        FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE post_comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    comment TEXT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    comment_deleted BOOLEAN NOT NULL,
    deleted_at TIMESTAMP(6),
    CONSTRAINT fk_post_comments_user
        FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_post_comments_post
        FOREIGN KEY (post_id) REFERENCES posts(post_id)
);

CREATE TABLE post_images (
    post_image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    create_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_post_images_post UNIQUE (post_id),
    CONSTRAINT fk_post_images_post
        FOREIGN KEY (post_id) REFERENCES posts(post_id)
);

CREATE TABLE post_likes (
    likes_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_post_likes_user_post UNIQUE (user_id, post_id),
    CONSTRAINT fk_post_likes_user
        FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_post_likes_post
        FOREIGN KEY (post_id) REFERENCES posts(post_id)
);

CREATE TABLE post_views (
    view_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    viewed_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_post_views_user_post UNIQUE (user_id, post_id),
    CONSTRAINT fk_post_views_user
        FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_post_views_post
        FOREIGN KEY (post_id) REFERENCES posts(post_id)
);

CREATE TABLE refresh_tokens (
    refresh_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_id VARCHAR(36) NOT NULL,
    family_id VARCHAR(36) NOT NULL,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revoked BOOLEAN NOT NULL,
    replaced_by_token_id VARCHAR(36),
    CONSTRAINT uk_refresh_tokens_token_id UNIQUE (token_id)
);
