CREATE TABLE bookmarks (
    bookmark_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,

    CONSTRAINT uk_bookmarks_user_post
        UNIQUE (user_id, post_id),

    CONSTRAINT fk_bookmarks_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id),

    CONSTRAINT fk_bookmarks_post
        FOREIGN KEY (post_id)
        REFERENCES posts(post_id)
);

CREATE INDEX idx_bookmarks_user_created_at
    ON bookmarks (user_id, created_at DESC, bookmark_id DESC);
