CREATE TABLE image_assets (
                              image_asset_id UUID PRIMARY KEY,
                              owner_user_id BIGINT NOT NULL,
                              image_type VARCHAR(20) NOT NULL,
                              status VARCHAR(20) NOT NULL,
                              created_at TIMESTAMP NOT NULL,
                              deleted_at TIMESTAMP,
                              purge_at TIMESTAMP,
                              delete_retry_count INT NOT NULL DEFAULT 0,
                              last_delete_error VARCHAR(500)
);

CREATE TABLE image_variants (
                                image_variant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                image_asset_id UUID NOT NULL,
                                variant_type VARCHAR(30) NOT NULL,
                                storage_path VARCHAR(500) NOT NULL,
                                width INT NOT NULL,
                                height INT NOT NULL,
                                mime_type VARCHAR(50) NOT NULL,
                                file_size BIGINT NOT NULL,
                                CONSTRAINT fk_image_variant_asset
                                    FOREIGN KEY (image_asset_id)
                                        REFERENCES image_assets(image_asset_id),
                                CONSTRAINT uk_image_variant_asset_type
                                    UNIQUE (image_asset_id, variant_type)
);

ALTER TABLE users
    ADD COLUMN profile_image_asset_id UUID;

ALTER TABLE users
    ALTER COLUMN profile_image DROP NOT NULL;

ALTER TABLE users
    ADD CONSTRAINT fk_users_profile_image_asset
        FOREIGN KEY (profile_image_asset_id)
            REFERENCES image_assets(image_asset_id);

CREATE INDEX idx_image_asset_purge
    ON image_assets(status, purge_at);